### ISSUE TITLE
Got no response from my bot

### ISSUE THREAD

**Issue by han3on** [flynnoct/chatgpt-telegram-bot#26]
wget command didn't work for me, so I used git clone to pull the source code, and I got all dependencies installed, sure, replaced the api key and bot token and got it running on my Azure WM, but I still got no response from my bot.

**Comment by flynnoct** [comment]
Sorry about the `wget` command. This is a known issue which we will fix in next version.

As for the bot won't working. Would you mind try this first? https://github.com/flynnoct/chatgpt-telegram-bot/issues/13

**Comment by han3on** [comment]
> Sorry about the `wget` command. This is a known issue which we will fix in next version.
> 
> 
> 
> As for the bot won't working. Would you mind try this first? https://github.com/flynnoct/chatgpt-telegram-bot/issues/13

Thanks for your reply, I have removed the comments and commas you mentioned, but it didn't help, I executed the openai_parser.py file and got response from openai.

**Comment by flynnoct** [comment]
You can just run `python3 telegram_message_parser.py` and see if there is any traceback info?

**Comment by han3on** [comment]
> 

Traceback (most recent call last):
  File "telegram_message_parser.py", line 15, in <module>
    from telegram import Update
ImportError: cannot import name 'Update' from 'telegram' (/home/ubuntu/.local/lib/python3.8/site-packages/telegram/__init__.py)

Thanks, I got traceback info as above.

**Comment by flynnoct** [comment]
Check this https://github.com/flynnoct/chatgpt-telegram-bot/issues/27.

Uninstall `telegram` module first and install `python-telegram-bot`

**Comment by han3on** [comment]
> Check this #27.
> 
> Uninstall `telegram` module first and install `python-telegram-bot`

Traceback (most recent call last):
  File "telegram_message_parser.py", line 22, in <module>
    with open("config.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

I got v1.2.0 on my VM, but still no response from my bot, I got trackback info as above when I run python3 telegram_message_parser.py

**Comment by DSwutang** [comment]
done in release 1.2.0

**Comment by han3on** [comment]
I moved config.json to folder src/, and the bot is working now, thanks.

**Comment by han3on** [comment]
> Sorry for mis-operation.
> 
> This is a brief explanation:
> 
> * If you run `python3 telegram_message_parser.py` in `src/` folder, it will try to read `config.json` from `src/` because this is your current working directory.
> * If you run this bot as we planned (execute `bash bin/start_bot.sh` in project's root directory), then it will try to load `config.json` from project's root directory which is we planned.
> * **Hence, if you want to run the bot manually, I suggest you to execute `python3 src/telegram_message_parser.py` because it will load config file from project's root directory. And no copy operation is needed.**
> 
> I hope this may help you.

Thanks for the explanatiom.

**Comment by flynnoct** [comment]
I will close this issue if everything is correct. Please comment if you have any further questions.
