### ISSUE TITLE
how to get working 

### ISSUE THREAD

**Issue by jimmywhite999** [flynnoct/chatgpt-telegram-bot#76]
ok its not my first time working with ai bots, iv followed all the instructions and ran it and nothing happens it wont responed or anything.

**Comment by RayCxggg** [comment]
Can you provide more information?

**Comment by kwikcoins** [comment]
I also get the bot running in terminal but the bit does not respond on telegram

**Comment by kwikcoins** [comment]
This is what I get when I try to use the config.py so I manually configured the config.json with my api keys

root@Auto:~/chatgpt-telegram-bot/bin# python config.pyTraceback (most recent call last):
  File "/root/chatgpt-telegram-bot/bin/config.py", line 215, in <module>
    config_dict = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 24 (char 179)
root@Auto:~/chatgpt-telegram-bot/bin#

**Comment by flynnoct** [comment]
@kwikcoins forget about config.py for now. Setup your **config.json** and then follow the instructions in README.md.

**Comment by flynnoct** [comment]
@jimmywhite999 plz provide more information that we can help you.

**Comment by rokipet** [comment]
is not working when i start the bot nothing happens
